# Generated by Django 2.2.7 on 2021-05-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(help_text='請輸入姓名', max_length=10)),
                ('gender', models.IntegerField()),
                ('favoriteCity', models.CharField(help_text='請輸入最喜歡的城市 (最多50字', max_length=50)),
                ('reason', models.TextField(help_text='請輸入喜歡該城市的理由 (最多300字)', max_length=300)),
                ('submitTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
