# Generated by Django 2.2.7 on 2021-05-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='gender',
            field=models.CharField(choices=[('n', '不透露'), ('m', '男'), ('f', '女')], default='n', help_text='請輸入性別', max_length=1),
        ),
    ]
