# Generated by Django 2.2.7 on 2021-05-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210505_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='gender',
            field=models.CharField(choices=[('不透露', '不透露'), ('男', '男'), ('女', '女')], default='n', help_text='請輸入性別', max_length=1),
        ),
    ]
